In [4]:
import numpy as np
i=np.array([10,20,30,40,50])
for j in i:
    print(j)

10
20
30
40
50


In [5]:
import numpy as np
i = np.array([[10, 20, 30], [40, 50, 60], [70,80,90]])
for j in i:
    print(j)

[10 20 30]
[40 50 60]
[70 80 90]


In [9]:
import numpy as np

i = np.array([[10, 20, 30], [40, 50, 60], [70,80,90]])

for j in i:
    for k in j:
        print(k)

10
20
30
40
50
60
70
80
90


In [10]:
import numpy as np 
i = np.array([
 [[10, 20, 30], [40, 50, 60], [70,80,90]],
 [[1, 2, 3], [4, 5, 6], [7,8,9]],
 [[10, 20, 30], [40, 50, 60], [70,80,90]],
 ])
for j in i :
    print(j)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [11]:
import numpy as np
i = np.array([
 [[10, 20, 30], [40, 50, 60], [70,80,90]],
 [[1, 2, 3], [4, 5, 6], [7,8,9]],
 [[10, 20, 30], [40, 50, 60], [70,80,90]],
 ])
for j in i:
    for k in j:
        for m in k:
            print(m)
        


10
20
30
40
50
60
70
80
90
1
2
3
4
5
6
7
8
9
10
20
30
40
50
60
70
80
90


In [14]:
from numpy import random
i=random.randint(10)
print(i)

3


In [16]:
from numpy import random
i=random.rand()
print(i)

0.9626464884772338


In [17]:
from numpy import random
i=random.rand(10)
print(i)

[0.39480814 0.46822344 0.50229306 0.37440565 0.98278911 0.36856599
 0.60787012 0.25485301 0.96943015 0.57084993]


In [19]:
from numpy import random
i=random.randint(100,size=(10))
print(i)

[96 15 34 27 39 65 24  0 19 84]


In [20]:
from numpy import random
i=random.randint(100,size=(3,5))
print(i)

[[ 7  4 61 40 22]
 [49  2 70 81 44]
 [ 1 69 91 25 51]]


In [21]:
from numpy import random
i=random.randint(100,size=(5,5))
print(i)

[[28 24 76 91 61]
 [28 92 60 23 72]
 [83 16 60 12 26]
 [69 37 72  2 46]
 [37 97 54 50 72]]


In [24]:
from numpy import random
i=random.randint(100,size=(3,5,2))
print(i)


[[[82 70]
  [61  1]
  [61 33]
  [25 30]
  [41 79]]

 [[79 89]
  [75 34]
  [33 10]
  [32 80]
  [67 73]]

 [[23 36]
  [13 98]
  [90 99]
  [99 32]
  [17  7]]]


In [27]:
from numpy import random
i=random.rand(3,5)
print(i)

[[0.23563859 0.00695101 0.23838852 0.53959426 0.17896445]
 [0.73407515 0.77056173 0.96647935 0.64748527 0.23015327]
 [0.27203969 0.89277689 0.88252593 0.05770629 0.10917918]]


In [1]:
from numpy import random
list1 = [10,20,30,40,50,60,70,80,90]
i=random.choice(list1)
print(i)

20


In [2]:
from numpy import random
list1 = [10,20,30,40,50,60,70]
i = random.choice(list1, size=(3, 5))
print(i)

[[50 10 70 60 20]
 [30 40 30 40 50]
 [20 50 60 50 20]]


In [3]:
from numpy import random
list1 = [10,20,30,40,50,60,70]
i = random.choice(list1, size=(3, 5, 2))
print(i)

[[[20 50]
  [50 70]
  [60 60]
  [70 10]
  [60 60]]

 [[70 50]
  [60 30]
  [50 60]
  [10 70]
  [60 70]]

 [[60 40]
  [60 70]
  [10 60]
  [10 70]
  [10 70]]]
